image_width: 1280
image_height: 960
camera_name: ov5647__base_soc_i2c0mux_i2c_1_ov5647_36_1280x960
camera_matrix:
  rows: 3
  cols: 3
  data: [4646.32307,    0.     ,  659.8242 ,
            0.     , 3913.61813,  476.12906,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-5.516477, 60.654077, -0.185515, -0.123044, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [4271.94482,    0.     ,  612.13556,    0.     ,
            0.     , 3561.87988,  426.88879,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
