/**:
  ros__parameters:
    height: 480
    width: 640
    role: still
    FrameDurationLimits: [ 100000, 100000 ]
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: reliable
