/**:
  ros__parameters:
    camera: 3
    height: 480
    width: 640
    format: 'YUYV'
    role: still
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: reliable
