/**:
  ros__parameters:
    camera: 0
    height: 1200
    width: 1600
    format: 'YUYV'
    role: 'still'
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1
          durability: 'volatile'
          history: 'keep_last'
          reliability: 'reliable'
