/**:
  ros__parameters:
    image_height: 480
    image_width: 640
    framerate: 10.0
    video_device: /dev/video0
    camera_name: video0
    camera_frame_id: video0
    camera_transport_suffix: video0_raw
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: reliable
